on: push
name: push
jobs:
  push-wincompile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: push-wincompile
      uses: ./.github/docker/wincompile
      env:
        CARGO_CFG_TARGET_FEATURE: crt-static
