on: release
name: release
jobs:
  release-wincompile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: release-wincompile
      uses: ./.github/docker/wincompile
      with:
        args: --release --out-dir out -Z unstable-options
    - name: release-publish
      uses: judge2020/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: out/*
    - name: release-Filter published
      uses: actions/bin/filter@master
      with:
        args: action published
